/* eslint-disable no-console */
const { PrismaClient } = require("@prisma/client");
const bcrypt = require("bcryptjs");

const prisma = new PrismaClient();

async function upsertUser(data) {
  return prisma.user.upsert({
    where: { email: data.email },
    update: data,
    create: data,
  });
}

async function upsertCitizen(data) {
  return prisma.citizen.upsert({
    where: { registrationNo: data.registrationNo },
    update: data,
    create: data,
  });
}

async function upsertTemplate(data) {
  const { id, ...updateData } = data;
  return prisma.certificateTemplate.upsert({
    where: { id },
    update: updateData,
    create: data,
  });
}

async function upsertCertificate(data) {
  return prisma.certificate.upsert({
    where: { referenceNo: data.referenceNo },
    update: data,
    create: data,
  });
}

async function upsertHoldingTax(data) {
  return prisma.holdingTax.upsert({
    where: { referenceNo: data.referenceNo },
    update: data,
    create: data,
  });
}

async function upsertReliefProgram(data) {
  return prisma.reliefProgram.upsert({
    where: { programCode: data.programCode },
    update: data,
    create: data,
  });
}

async function upsertBeneficiary(data) {
  return prisma.beneficiary.upsert({
    where: { beneficiaryNo: data.beneficiaryNo },
    update: data,
    create: data,
  });
}

async function upsertCashbook(data) {
  return prisma.cashbook.upsert({
    where: { entryNo: data.entryNo },
    update: data,
    create: data,
  });
}

async function upsertNotification(data) {
  const { id, ...updateData } = data;
  return prisma.notification.upsert({
    where: { id },
    update: updateData,
    create: data,
  });
}

async function upsertSetting(data) {
  return prisma.setting.upsert({
    where: { key: data.key },
    update: data,
    create: data,
  });
}

async function seed() {
  const hashedPassword = await bcrypt.hash("Dev@12345", 12);

  const union = await prisma.unionParishad.upsert({
    where: { code: "UP-001" },
    update: {
      nameEn: "Kanchanpur Union Parishad",
      nameBn: "কাঞ্চনপুর ইউনিয়ন পরিষদ",
      district: "Cumilla",
      upazila: "Burichong",
      division: "Chattogram",
      chairman: "Md. Harunur Rashid",
      chairmanPhone: "01710000001",
      totalWards: 9,
      address: "Kanchanpur, Burichong, Cumilla",
      phone: "081-123456",
      email: "info@kanchanpurup.gov.bd",
      website: "https://kanchanpurup.gov.bd",
    },
    create: {
      code: "UP-001",
      nameEn: "Kanchanpur Union Parishad",
      nameBn: "কাঞ্চনপুর ইউনিয়ন পরিষদ",
      district: "Cumilla",
      upazila: "Burichong",
      division: "Chattogram",
      chairman: "Md. Harunur Rashid",
      chairmanPhone: "01710000001",
      totalWards: 9,
      address: "Kanchanpur, Burichong, Cumilla",
      phone: "081-123456",
      email: "info@kanchanpurup.gov.bd",
      website: "https://kanchanpurup.gov.bd",
    },
  });

  const secretary = await upsertUser({
    email: "secretary@smartunion.local",
    password: hashedPassword,
    name: "Union Secretary",
    nameEn: "Union Secretary",
    nameBn: "ইউনিয়ন সচিব",
    phone: "01710000002",
    role: "SECRETARY",
    status: "ACTIVE",
  });

  const entrepreneur = await upsertUser({
    email: "entrepreneur@smartunion.local",
    password: hashedPassword,
    name: "Union Entrepreneur",
    nameEn: "Union Entrepreneur",
    nameBn: "ইউনিয়ন উদ্যোক্তা",
    phone: "01710000003",
    role: "ENTREPRENEUR",
    status: "ACTIVE",
  });

  const citizenRows = [
    {
      registrationNo: "CIT-2026-W01-00001",
      nid: "19911234567800001",
      birthCertificateNo: "BC-1991-00001",
      passportNo: "A12345001",
      name: "Abdul Karim",
      nameEn: "Abdul Karim",
      nameBn: "আব্দুল করিম",
      fatherName: "Rahim Uddin",
      fatherNameBn: "রহিম উদ্দিন",
      motherName: "Amena Begum",
      motherNameBn: "আমেনা বেগম",
      spouseName: "Rokeya Begum",
      dateOfBirth: new Date("1991-04-15"),
      gender: "MALE",
      bloodGroup: "B_POSITIVE",
      religion: "Islam",
      maritalStatus: "MARRIED",
      occupation: "Farmer",
      education: "SSC",
      income: 240000,
      mobile: "01711000001",
      email: "abdul.karim@example.com",
      presentAddress: {
        village: "Kanchanpur",
        ward: 1,
        postOffice: "Kanchanpur",
        postCode: "3520",
        upazila: "Burichong",
        district: "Cumilla",
        division: "Chattogram",
        fullAddress: "Village Kanchanpur, Ward 1, Burichong, Cumilla",
      },
      permanentAddress: {
        village: "Kanchanpur",
        ward: 1,
        postOffice: "Kanchanpur",
        postCode: "3520",
        upazila: "Burichong",
        district: "Cumilla",
        division: "Chattogram",
        fullAddress: "Village Kanchanpur, Ward 1, Burichong, Cumilla",
      },
      holdingNo: "H-1-101",
      voterNo: "VOT-10001",
      isFreedomFighter: false,
      isDisabled: false,
      isWidow: false,
      isOrphan: false,
      familyMembersCount: 5,
      status: "ACTIVE",
      verifiedAt: new Date("2026-01-15"),
      verifiedById: secretary.id,
      unionParishadId: union.id,
      createdById: entrepreneur.id,
      updatedById: entrepreneur.id,
      metadata: { householdType: "Joint", notes: "Demo household 1" },
    },
    {
      registrationNo: "CIT-2026-W02-00001",
      nid: "19880234567800002",
      birthCertificateNo: "BC-1988-00002",
      passportNo: "A12345002",
      name: "Fatema Khatun",
      nameEn: "Fatema Khatun",
      nameBn: "ফাতেমা খাতুন",
      fatherName: "Jalal Miah",
      fatherNameBn: "জালাল মিয়া",
      motherName: "Hasina Begum",
      motherNameBn: "হাসিনা বেগম",
      spouseName: "Mizanur Rahman",
      dateOfBirth: new Date("1988-09-10"),
      gender: "FEMALE",
      bloodGroup: "O_POSITIVE",
      religion: "Islam",
      maritalStatus: "MARRIED",
      occupation: "Homemaker",
      education: "HSC",
      income: 180000,
      mobile: "01711000002",
      email: "fatema.khatun@example.com",
      presentAddress: {
        village: "Shibpur",
        ward: 2,
        postOffice: "Shibpur",
        postCode: "3521",
        upazila: "Burichong",
        district: "Cumilla",
        division: "Chattogram",
        fullAddress: "Village Shibpur, Ward 2, Burichong, Cumilla",
      },
      permanentAddress: {
        village: "Shibpur",
        ward: 2,
        postOffice: "Shibpur",
        postCode: "3521",
        upazila: "Burichong",
        district: "Cumilla",
        division: "Chattogram",
        fullAddress: "Village Shibpur, Ward 2, Burichong, Cumilla",
      },
      holdingNo: "H-2-205",
      voterNo: "VOT-10002",
      isFreedomFighter: false,
      isDisabled: false,
      isWidow: false,
      isOrphan: false,
      familyMembersCount: 4,
      status: "ACTIVE",
      verifiedAt: new Date("2026-01-16"),
      verifiedById: secretary.id,
      unionParishadId: union.id,
      createdById: entrepreneur.id,
      updatedById: entrepreneur.id,
      metadata: { householdType: "Nuclear", notes: "Demo household 2" },
    },
    {
      registrationNo: "CIT-2026-W03-00001",
      nid: "19750345678900003",
      birthCertificateNo: "BC-1975-00003",
      passportNo: "A12345003",
      name: "Gopal Chandra Das",
      nameEn: "Gopal Chandra Das",
      nameBn: "গোপাল চন্দ্র দাস",
      fatherName: "Niranjan Das",
      motherName: "Shanti Rani",
      dateOfBirth: new Date("1975-01-22"),
      gender: "MALE",
      bloodGroup: "A_POSITIVE",
      religion: "Hindu",
      maritalStatus: "MARRIED",
      occupation: "Shopkeeper",
      education: "Class 10",
      income: 360000,
      mobile: "01711000003",
      email: "gopal.das@example.com",
      presentAddress: {
        village: "Balina",
        ward: 3,
        postOffice: "Balina",
        postCode: "3522",
        upazila: "Burichong",
        district: "Cumilla",
        division: "Chattogram",
        fullAddress: "Village Balina, Ward 3, Burichong, Cumilla",
      },
      permanentAddress: {
        village: "Balina",
        ward: 3,
        postOffice: "Balina",
        postCode: "3522",
        upazila: "Burichong",
        district: "Cumilla",
        division: "Chattogram",
        fullAddress: "Village Balina, Ward 3, Burichong, Cumilla",
      },
      holdingNo: "H-3-310",
      voterNo: "VOT-10003",
      isFreedomFighter: true,
      isDisabled: false,
      isWidow: false,
      isOrphan: false,
      familyMembersCount: 6,
      status: "ACTIVE",
      verifiedAt: new Date("2026-01-17"),
      verifiedById: secretary.id,
      unionParishadId: union.id,
      createdById: entrepreneur.id,
      updatedById: entrepreneur.id,
      metadata: { freedomFighterNo: "FF-0003", notes: "Priority for relief" },
    },
    {
      registrationNo: "CIT-2026-W04-00001",
      nid: "19950456789000004",
      birthCertificateNo: "BC-1995-00004",
      passportNo: "A12345004",
      name: "Shila Akter",
      nameEn: "Shila Akter",
      nameBn: "শিলা আক্তার",
      fatherName: "Kashem Ali",
      motherName: "Renu Begum",
      dateOfBirth: new Date("1995-12-05"),
      gender: "FEMALE",
      bloodGroup: "AB_POSITIVE",
      religion: "Islam",
      maritalStatus: "WIDOWED",
      occupation: "Tailor",
      education: "JSC",
      income: 120000,
      mobile: "01711000004",
      email: "shila.akter@example.com",
      presentAddress: {
        village: "Mokam",
        ward: 4,
        postOffice: "Mokam",
        postCode: "3523",
        upazila: "Burichong",
        district: "Cumilla",
        division: "Chattogram",
        fullAddress: "Village Mokam, Ward 4, Burichong, Cumilla",
      },
      permanentAddress: {
        village: "Mokam",
        ward: 4,
        postOffice: "Mokam",
        postCode: "3523",
        upazila: "Burichong",
        district: "Cumilla",
        division: "Chattogram",
        fullAddress: "Village Mokam, Ward 4, Burichong, Cumilla",
      },
      holdingNo: "H-4-410",
      voterNo: "VOT-10004",
      isFreedomFighter: false,
      isDisabled: true,
      disabilityType: "Locomotor",
      isWidow: true,
      isOrphan: false,
      familyMembersCount: 3,
      status: "ACTIVE",
      verifiedAt: new Date("2026-01-18"),
      verifiedById: secretary.id,
      unionParishadId: union.id,
      createdById: entrepreneur.id,
      updatedById: entrepreneur.id,
      metadata: { socialSafetyNet: true, notes: "Widow allowance candidate" },
    },
    {
      registrationNo: "CIT-2026-W05-00001",
      nid: "20010678901200005",
      birthCertificateNo: "BC-2001-00005",
      passportNo: "A12345005",
      name: "Rubel Hossain",
      nameEn: "Rubel Hossain",
      nameBn: "রুবেল হোসেন",
      fatherName: "Babul Miah",
      motherName: "Salma Akter",
      dateOfBirth: new Date("2001-07-30"),
      gender: "MALE",
      bloodGroup: "O_NEGATIVE",
      religion: "Islam",
      maritalStatus: "SINGLE",
      occupation: "Student",
      education: "Honours",
      income: 60000,
      mobile: "01711000005",
      email: "rubel.hossain@example.com",
      presentAddress: {
        village: "Madhabpur",
        ward: 5,
        postOffice: "Madhabpur",
        postCode: "3524",
        upazila: "Burichong",
        district: "Cumilla",
        division: "Chattogram",
        fullAddress: "Village Madhabpur, Ward 5, Burichong, Cumilla",
      },
      permanentAddress: {
        village: "Madhabpur",
        ward: 5,
        postOffice: "Madhabpur",
        postCode: "3524",
        upazila: "Burichong",
        district: "Cumilla",
        division: "Chattogram",
        fullAddress: "Village Madhabpur, Ward 5, Burichong, Cumilla",
      },
      holdingNo: "H-5-502",
      voterNo: "VOT-10005",
      isFreedomFighter: false,
      isDisabled: false,
      isWidow: false,
      isOrphan: true,
      familyMembersCount: 2,
      status: "ACTIVE",
      verifiedAt: new Date("2026-01-19"),
      verifiedById: secretary.id,
      unionParishadId: union.id,
      createdById: entrepreneur.id,
      updatedById: entrepreneur.id,
      metadata: { studentId: "STD-1005", notes: "Education relief candidate" },
    },
  ];

  const citizens = [];
  for (const citizenData of citizenRows) {
    citizens.push(await upsertCitizen(citizenData));
  }

  for (let i = 0; i < 3; i += 1) {
    await upsertUser({
      email: `citizen${i + 1}@smartunion.local`,
      password: hashedPassword,
      name: citizens[i].name,
      nameEn: citizens[i].nameEn,
      nameBn: citizens[i].nameBn,
      phone: citizens[i].mobile,
      role: "CITIZEN",
      status: "ACTIVE",
      citizenId: citizens[i].id,
    });
  }

  const templateData = [
    { type: "BIRTH", fee: 50, validityDays: 3650, label: "Birth Certificate" },
    { type: "DEATH", fee: 50, validityDays: 3650, label: "Death Certificate" },
    { type: "CITIZENSHIP", fee: 100, validityDays: 3650, label: "Citizenship Certificate" },
    { type: "CHARACTER", fee: 120, validityDays: 180, label: "Character Certificate" },
    { type: "INHERITORSHIP", fee: 200, validityDays: 365, label: "Inheritorship Certificate" },
    { type: "TRADE_LICENSE", fee: 500, validityDays: 365, label: "Trade License Certificate" },
    { type: "NOC", fee: 150, validityDays: 180, label: "No Objection Certificate" },
  ];

  const templateIds = {
    BIRTH: "65f100000000000000000001",
    DEATH: "65f100000000000000000002",
    CITIZENSHIP: "65f100000000000000000003",
    CHARACTER: "65f100000000000000000004",
    INHERITORSHIP: "65f100000000000000000005",
    TRADE_LICENSE: "65f100000000000000000006",
    NOC: "65f100000000000000000007",
  };

  const templates = {};
  for (const t of templateData) {
    templates[t.type] = await upsertTemplate({
      id: templateIds[t.type],
      name: t.label,
      nameEn: t.label,
      nameBn: `${t.label} (বাংলা)`,
      certificateType: t.type,
      description: `${t.label} template for testing`,
      version: 1,
      status: "ACTIVE",
      fee: t.fee,
      validityDays: t.validityDays,
      headerHtml: "<h2 style='text-align:center'>Union Parishad Certificate</h2>",
      bodyHtml:
        "<p>This certifies that <strong>{{name}}</strong>, child of {{father_name}}, is a resident of this union.</p>",
      footerHtml: "<p style='text-align:center'>Issued by Union Parishad Authority</p>",
      stylesCss: "body{font-family:'Noto Sans Bengali',Arial,sans-serif;font-size:14px;}",
      fields: [
        {
          name: "name",
          label: "Applicant Name",
          labelBn: "আবেদনকারীর নাম",
          type: "text",
          required: true,
          options: [],
          order: 1,
        },
        {
          name: "father_name",
          label: "Father's Name",
          labelBn: "পিতার নাম",
          type: "text",
          required: false,
          options: [],
          order: 2,
        },
      ],
      placeholders: ["{{name}}", "{{father_name}}"],
      paperSize: "A4",
      orientation: "portrait",
      marginTop: 20,
      marginBottom: 20,
      marginLeft: 20,
      marginRight: 20,
      showQrCode: true,
      qrPosition: "bottom-right",
      showLogo: true,
      showSeal: true,
      showWatermark: false,
      showBorder: true,
      borderStyle: "1px solid #111827",
      isDefault: t.type === "CITIZENSHIP",
      unionParishadId: union.id,
      createdById: secretary.id,
      updatedById: secretary.id,
      deletedAt: null,
    });
  }

  const certificateRows = [
    {
      certificateNo: "BIR-2026-000001",
      referenceNo: "REF-BIR-2026-000001",
      type: "BIRTH",
      citizen: citizens[0],
      template: templates.BIRTH,
      status: "APPROVED",
      note: "Birth details verified from registry.",
    },
    {
      certificateNo: "DEA-2026-000001",
      referenceNo: "REF-DEA-2026-000001",
      type: "DEATH",
      citizen: citizens[1],
      template: templates.DEATH,
      status: "PENDING",
      note: "Awaiting final approval.",
    },
    {
      certificateNo: "CIT-2026-000001",
      referenceNo: "REF-CIT-2026-000001",
      type: "CITIZENSHIP",
      citizen: citizens[2],
      template: templates.CITIZENSHIP,
      status: "APPROVED",
      note: "Citizenship certificate approved.",
    },
    {
      certificateNo: "CHA-2026-000001",
      referenceNo: "REF-CHA-2026-000001",
      type: "CHARACTER",
      citizen: citizens[3],
      template: templates.CHARACTER,
      status: "REJECTED",
      note: "Insufficient supporting documents.",
    },
    {
      certificateNo: "INH-2026-000001",
      referenceNo: "REF-INH-2026-000001",
      type: "INHERITORSHIP",
      citizen: citizens[0],
      template: templates.INHERITORSHIP,
      status: "APPROVED",
      note: "Heir list matched with records.",
    },
    {
      certificateNo: "TRA-2026-000001",
      referenceNo: "REF-TRA-2026-000001",
      type: "TRADE_LICENSE",
      citizen: citizens[2],
      template: templates.TRADE_LICENSE,
      status: "PENDING",
      note: "Field verification ongoing.",
    },
    {
      certificateNo: "NOC-2026-000001",
      referenceNo: "REF-NOC-2026-000001",
      type: "NOC",
      citizen: citizens[4],
      template: templates.NOC,
      status: "APPROVED",
      note: "No objection granted.",
    },
  ];

  for (const c of certificateRows) {
    await upsertCertificate({
      certificateNo: c.certificateNo,
      referenceNo: c.referenceNo,
      type: c.type,
      citizenId: c.citizen.id,
      templateId: c.template.id,
      applicantName: c.citizen.name,
      applicantNameBn: c.citizen.nameBn,
      issuedById: entrepreneur.id,
      issuedAt: new Date("2026-02-10T10:00:00.000Z"),
      validUntil: new Date("2027-02-10T10:00:00.000Z"),
      status: c.status,
      approvedAt: c.status === "APPROVED" ? new Date("2026-02-11T10:00:00.000Z") : null,
      approvedById: c.status === "APPROVED" ? secretary.id : null,
      rejectedAt: c.status === "REJECTED" ? new Date("2026-02-12T10:00:00.000Z") : null,
      rejectionReason: c.status === "REJECTED" ? c.note : null,
      qrCode: c.referenceNo,
      verificationUrl: `/verify/${c.referenceNo}`,
      finalText: `${c.type} certificate issued for ${c.citizen.name}`,
      metadata: {
        birthPlace: "Cumilla",
        customFields: { note: c.note, seeded: true },
      },
      printCount: c.status === "APPROVED" ? 1 : 0,
      lastPrintedAt: c.status === "APPROVED" ? new Date("2026-02-12T12:00:00.000Z") : null,
      printHistory:
        c.status === "APPROVED"
          ? [
              {
                printedAt: new Date("2026-02-12T12:00:00.000Z"),
                printedById: entrepreneur.id,
                method: "SYSTEM",
                note: "Seed print",
              },
            ]
          : [],
      fee: c.template.fee,
      feeStatus: c.status === "APPROVED" ? "PAID" : "UNPAID",
      unionParishadId: union.id,
      createdById: entrepreneur.id,
      updatedById: secretary.id,
      deletedAt: null,
    });
  }

  await upsertHoldingTax({
    referenceNo: "HT-20252026-W01-00001",
    citizenId: citizens[0].id,
    holdingInfo: {
      holdingNo: "H-1-101",
      mouza: "Kanchanpur",
      ward: 1,
      area: 5.5,
      areaUnit: "decimal",
      holdingType: "RESIDENTIAL",
      buildingType: "SEMI_PUCCA",
      floors: 1,
      rooms: 4,
      yearBuilt: 2012,
    },
    fiscalYear: "2025-2026",
    assessment: {
      assessedValue: 900000,
      taxRate: 0.05,
      annualTax: 4500,
      assessmentDate: new Date("2025-07-15"),
      assessedById: secretary.id,
      notes: "Regular annual assessment",
    },
    arrears: 1000,
    rebate: 200,
    penalty: 100,
    totalDue: 5400,
    totalPaid: 3000,
    balance: 2400,
    dueDate: new Date("2026-06-30"),
    status: "PARTIAL",
    payments: [
      {
        receiptNo: "RCP-20252026-000001",
        amount: 3000,
        paymentDate: new Date("2026-01-10"),
        paymentMethod: "CASH",
        transactionId: "TX-HT-001",
        collectedById: entrepreneur.id,
        notes: "First installment",
        createdAt: new Date("2026-01-10"),
        updatedAt: new Date("2026-01-10"),
      },
    ],
    lastPaymentDate: new Date("2026-01-10"),
    demandNoticeDate: new Date("2026-02-01"),
    demandNoticeSent: true,
    unionParishadId: union.id,
    createdById: entrepreneur.id,
    updatedById: entrepreneur.id,
    deletedAt: null,
  });

  await upsertHoldingTax({
    referenceNo: "HT-20252026-W03-00001",
    citizenId: citizens[2].id,
    holdingInfo: {
      holdingNo: "H-3-310",
      mouza: "Balina",
      ward: 3,
      area: 3.2,
      areaUnit: "decimal",
      holdingType: "COMMERCIAL",
      buildingType: "PUCCA",
      floors: 2,
      rooms: 8,
      yearBuilt: 2015,
    },
    fiscalYear: "2025-2026",
    assessment: {
      assessedValue: 1500000,
      taxRate: 0.06,
      annualTax: 9000,
      assessmentDate: new Date("2025-07-20"),
      assessedById: secretary.id,
      notes: "Commercial rate",
    },
    arrears: 0,
    rebate: 0,
    penalty: 0,
    totalDue: 9000,
    totalPaid: 9000,
    balance: 0,
    dueDate: new Date("2026-06-30"),
    status: "PAID",
    payments: [
      {
        receiptNo: "RCP-20252026-000002",
        amount: 9000,
        paymentDate: new Date("2025-12-22"),
        paymentMethod: "MOBILE_BANKING",
        transactionId: "TX-HT-002",
        bankName: "bKash",
        collectedById: entrepreneur.id,
        notes: "Full payment",
        createdAt: new Date("2025-12-22"),
        updatedAt: new Date("2025-12-22"),
      },
    ],
    lastPaymentDate: new Date("2025-12-22"),
    demandNoticeSent: false,
    unionParishadId: union.id,
    createdById: entrepreneur.id,
    updatedById: entrepreneur.id,
    deletedAt: null,
  });

  const floodProgram = await upsertReliefProgram({
    programCode: "RP-DIS-2026-0001",
    name: "Flood Emergency Support 2026",
    nameEn: "Flood Emergency Support 2026",
    nameBn: "বন্যা জরুরি সহায়তা ২০২৬",
    description: "Emergency food and cash support for flood affected households.",
    type: "DISASTER",
    category: "Emergency",
    status: "ACTIVE",
    fundingSource: "GOVERNMENT",
    fundingAgency: "Ministry of Disaster Management",
    startDate: new Date("2026-01-01"),
    endDate: new Date("2026-06-30"),
    eligibilityCriteria: {
      maxIncome: 250000,
      wards: [1, 2, 4, 5],
      isDisabled: true,
      isWidow: true,
      customCriteria: "Priority for vulnerable families",
    },
    budget: {
      totalBudget: 3000000,
      allocatedBudget: 1200000,
      disbursedAmount: 850000,
      remainingAmount: 2150000,
      costPerBeneficiary: 10000,
      currency: "BDT",
    },
    targetBeneficiaries: 300,
    currentBeneficiaries: 2,
    distributionSchedule: "Monthly",
    distributionMethod: "Mobile Banking + Food package",
    itemsDistributed: [
      { name: "Rice", quantity: 20, unit: "kg" },
      { name: "Lentil", quantity: 2, unit: "kg" },
      { name: "Cooking Oil", quantity: 2, unit: "liter" },
    ],
    documents: ["flood_assessment_report_2026.pdf"],
    contactPerson: "Relief Officer",
    contactPhone: "01711009999",
    unionParishadId: union.id,
    createdById: secretary.id,
    updatedById: secretary.id,
    deletedAt: null,
  });

  const educationProgram = await upsertReliefProgram({
    programCode: "RP-EDU-2026-0001",
    name: "Merit Scholarship Program 2026",
    nameEn: "Merit Scholarship Program 2026",
    nameBn: "মেধাবৃত্তি কর্মসূচি ২০২৬",
    description: "Scholarship support for underprivileged students.",
    type: "EDUCATION",
    category: "Scholarship",
    status: "PLANNED",
    fundingSource: "NGO",
    fundingAgency: "Smart Future Foundation",
    startDate: new Date("2026-03-01"),
    endDate: new Date("2026-12-31"),
    eligibilityCriteria: {
      maxAge: 25,
      maxIncome: 180000,
      wards: [5, 6, 7],
      isOrphan: true,
      customCriteria: "Must be currently enrolled",
    },
    budget: {
      totalBudget: 1200000,
      allocatedBudget: 300000,
      disbursedAmount: 0,
      remainingAmount: 1200000,
      costPerBeneficiary: 20000,
      currency: "BDT",
    },
    targetBeneficiaries: 60,
    currentBeneficiaries: 1,
    distributionSchedule: "Quarterly",
    distributionMethod: "Bank transfer",
    itemsDistributed: [],
    documents: ["scholarship_policy_2026.pdf"],
    contactPerson: "Education Officer",
    contactPhone: "01711008888",
    unionParishadId: union.id,
    createdById: secretary.id,
    updatedById: secretary.id,
    deletedAt: null,
  });

  await upsertBeneficiary({
    beneficiaryNo: "BEN-RP-DIS-2026-0001-00001",
    programId: floodProgram.id,
    citizenId: citizens[3].id,
    applicationDate: new Date("2026-01-05"),
    status: "ACTIVE",
    priorityScore: 95,
    priorityReason: "Widow and disabled",
    verifiedAt: new Date("2026-01-06"),
    verifiedById: secretary.id,
    approvedAt: new Date("2026-01-07"),
    approvedById: secretary.id,
    totalEntitlement: 30000,
    totalReceived: 10000,
    remainingEntitlement: 20000,
    distributions: [
      {
        distributionNo: "DIST-BEN-RP-DIS-2026-0001-00001-001",
        scheduledDate: new Date("2026-01-10"),
        distributedDate: new Date("2026-01-10"),
        status: "DISTRIBUTED",
        amount: 10000,
        items: [{ name: "Food Package", quantity: 1, unit: "pack" }],
        collectedBy: "Shila Akter",
        collectorRelation: "Self",
        distributedById: entrepreneur.id,
        receiptNo: "REL-REC-0001",
        remarks: "Delivered successfully",
        createdAt: new Date("2026-01-10"),
        updatedAt: new Date("2026-01-10"),
      },
    ],
    lastDistributionDate: new Date("2026-01-10"),
    nextDistributionDate: new Date("2026-03-10"),
    mobileBanking: {
      provider: "bKash",
      accountNo: "01711000004",
    },
    nomineeName: "Rumi Akter",
    nomineeRelation: "Daughter",
    nomineePhone: "01720000004",
    documents: ["nid_shila.pdf", "disability_card_shila.pdf"],
    notes: "High-priority disaster relief recipient",
    isLocked: false,
    unionParishadId: union.id,
    createdById: secretary.id,
    updatedById: secretary.id,
    deletedAt: null,
  });

  await upsertBeneficiary({
    beneficiaryNo: "BEN-RP-EDU-2026-0001-00001",
    programId: educationProgram.id,
    citizenId: citizens[4].id,
    applicationDate: new Date("2026-03-05"),
    status: "VERIFIED",
    priorityScore: 85,
    priorityReason: "Orphan student with low income",
    verifiedAt: new Date("2026-03-06"),
    verifiedById: secretary.id,
    totalEntitlement: 20000,
    totalReceived: 0,
    remainingEntitlement: 20000,
    distributions: [],
    nextDistributionDate: new Date("2026-04-15"),
    bankAccount: {
      bankName: "Sonali Bank",
      branchName: "Burichong",
      accountNo: "1234567890",
      accountName: "Rubel Hossain",
    },
    nomineeName: "Salma Akter",
    nomineeRelation: "Mother",
    nomineePhone: "01730000005",
    documents: ["student_id_rubel.pdf", "orphan_certificate_rubel.pdf"],
    notes: "Ready for first scholarship disbursement",
    isLocked: false,
    unionParishadId: union.id,
    createdById: secretary.id,
    updatedById: secretary.id,
    deletedAt: null,
  });

  await upsertCashbook({
    entryNo: "CB-20252026-IN-00001",
    voucherNo: "VCH-IN-0001",
    transactionDate: new Date("2026-01-10"),
    transactionType: "INCOME",
    category: "HOLDING_TAX",
    description: "Holding tax collection for Ward 1",
    descriptionBn: "ওয়ার্ড ১ হোল্ডিং ট্যাক্স আদায়",
    amount: 3000,
    paymentMode: "CASH",
    referenceNo: "RCP-20252026-000001",
    referenceType: "HOLDING_TAX",
    receivedFrom: "Abdul Karim",
    fiscalYear: "2025-2026",
    openingBalance: 100000,
    closingBalance: 103000,
    status: "APPROVED",
    approvedAt: new Date("2026-01-10"),
    approvedById: secretary.id,
    unionParishadId: union.id,
    createdById: entrepreneur.id,
    updatedById: entrepreneur.id,
    attachments: [],
    deletedAt: null,
  });

  await upsertCashbook({
    entryNo: "CB-20252026-EX-00001",
    voucherNo: "VCH-EX-0001",
    transactionDate: new Date("2026-01-12"),
    transactionType: "EXPENSE",
    category: "RELIEF_DISTRIBUTION",
    description: "Flood relief cash disbursement",
    descriptionBn: "বন্যা সহায়তা নগদ বিতরণ",
    amount: 10000,
    paymentMode: "MOBILE_BANKING",
    referenceNo: "REL-REC-0001",
    referenceType: "RELIEF",
    paidTo: "Shila Akter",
    transactionId: "MB-REL-0001",
    fiscalYear: "2025-2026",
    openingBalance: 103000,
    closingBalance: 93000,
    status: "APPROVED",
    approvedAt: new Date("2026-01-12"),
    approvedById: secretary.id,
    unionParishadId: union.id,
    createdById: entrepreneur.id,
    updatedById: entrepreneur.id,
    attachments: [],
    deletedAt: null,
  });

  await upsertNotification({
    id: "65f200000000000000000001",
    recipientId: entrepreneur.id,
    recipientType: "user",
    recipientEmail: entrepreneur.email,
    senderId: secretary.id,
    type: "SUCCESS",
    category: "CERTIFICATE",
    channel: "IN_APP",
    title: "Certificate approved",
    titleBn: "সনদ অনুমোদিত",
    message: "REF-CIT-2026-000001 has been approved.",
    messageBn: "REF-CIT-2026-000001 সনদটি অনুমোদিত হয়েছে।",
    link: "/dashboard/certificates",
    linkText: "View certificate",
    entityType: "CERTIFICATE",
    priority: 5,
    status: "READ",
    sentAt: new Date("2026-02-11T10:30:00.000Z"),
    deliveredAt: new Date("2026-02-11T10:30:05.000Z"),
    readAt: new Date("2026-02-11T12:00:00.000Z"),
    unionParishadId: union.id,
    isArchived: false,
    retryCount: 0,
    maxRetries: 3,
    deletedAt: null,
  });

  await upsertNotification({
    id: "65f200000000000000000002",
    recipientId: secretary.id,
    recipientType: "user",
    recipientEmail: secretary.email,
    senderId: entrepreneur.id,
    type: "WARNING",
    category: "TAX",
    channel: "IN_APP",
    title: "Holding tax overdue alert",
    titleBn: "হোল্ডিং ট্যাক্স বকেয়া সতর্কতা",
    message: "Citizen Abdul Karim still has balance due: 2400 BDT.",
    messageBn: "নাগরিক আব্দুল করিমের ২৪০০ টাকা বকেয়া আছে।",
    link: "/dashboard/holding-tax",
    linkText: "Review tax record",
    entityType: "HOLDING_TAX",
    priority: 8,
    status: "SENT",
    sentAt: new Date("2026-02-15T08:00:00.000Z"),
    unionParishadId: union.id,
    isArchived: false,
    retryCount: 0,
    maxRetries: 3,
    deletedAt: null,
  });

  await upsertSetting({
    key: "system.defaultLanguage",
    value: "bn",
    type: "string",
    description: "Default application language",
  });

  await upsertSetting({
    key: "certificate.defaultValidityDays",
    value: "365",
    type: "number",
    description: "Default validity days for standard certificates",
  });

  await upsertSetting({
    key: "union.currentFiscalYear",
    value: "2025-2026",
    type: "string",
    description: "Current fiscal year in use",
  });

  const counts = await Promise.all([
    prisma.unionParishad.count(),
    prisma.user.count(),
    prisma.citizen.count(),
    prisma.certificateTemplate.count(),
    prisma.certificate.count(),
    prisma.holdingTax.count(),
    prisma.reliefProgram.count(),
    prisma.beneficiary.count(),
    prisma.cashbook.count(),
    prisma.notification.count(),
    prisma.setting.count(),
  ]);

  console.log("Seed completed successfully.");
  console.log({
    unionParishads: counts[0],
    users: counts[1],
    citizens: counts[2],
    certificateTemplates: counts[3],
    certificates: counts[4],
    holdingTaxes: counts[5],
    reliefPrograms: counts[6],
    beneficiaries: counts[7],
    cashbookEntries: counts[8],
    notifications: counts[9],
    settings: counts[10],
  });
}

seed()
  .catch((error) => {
    console.error("Seed failed:", error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
